FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

# Копируем файл проекта (он лежит прямо тут) и восстанавливаем зависимости
COPY ["FinalProjectDSS.csproj", "./"]
RUN dotnet restore "FinalProjectDSS.csproj"

# Копируем весь остальной код
COPY . .
RUN dotnet publish "FinalProjectDSS.csproj" -c Release -o /app/publish

# Создаем финальный образ для работы
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
COPY --from=build /app/publish .

# Указываем порты из спецификации
EXPOSE 3087
ENV ASPNETCORE_URLS=http://+:3087

ENTRYPOINT ["dotnet", "FinalProjectDSS.dll"]