version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: todo_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5671
      POSTGRES_DB: TodoDb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: todo_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: todo_rabbitmq
    environment:
      # Создаем админа, чтобы пускал по сети
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: todo_api
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=TodoDb;Username=postgres;Password=5671
      - Jwt__Key=SuperSecretKeyThatIsAtLeast32CharactersLong!
      - Jwt__Issuer=TodoApi
      - Jwt__Audience=TodoApiClient
      - ASPNETCORE_ENVIRONMENT=Development
      
      - RedisConnection=redis:6379,abortConnect=false
      - RabbitHost=rabbitmq
      - RabbitUser=admin
      - RabbitPass=admin123
    ports:
      - "3087:3087"
    depends_on:
      - db
      - redis
      - rabbitmq

volumes:
  pgdata: